### ISSUE TITLE
Could not load 'plugins/RealEconomy-1.13.1.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by pandory-network** [MillcreekServer/RealEconomy#4]
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: io/github/wysohn/rapidframework3/bukkit/main/AbstractBukkitPlugin

**Plugin Version**
RapidFramework-3.14.11-all.jar
RealEconomy-1.13.1.jar

**Log:** https://gist.github.com/pandory-network/a72686a22c1ee571fc0c1cbab4a9ff2b

**Comment by wysohn** [comment]
Hello,

Sounds like a dependency order issue.

I'm not quite sure why this happened at all.

Do you mind actually upload the jar files?

I need to see how plugin.yml is formed.

**Comment by pandory-network** [comment]
which jar files should I upload?  all will not be possible there are some premium plugins included.

**Comment by pandory-network** [comment]
i have solved the problem for me 

https://github.com/MillcreekServer/RealEconomy/pull/5

**Comment by wysohn** [comment]
68a4784fb11622596502a7bfb620684daf26f5ae
